
[functions.sync-user-to-users-table]
enabled = true
verify_jwt = true
import_map = "./functions/sync-user-to-users-table/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sync-user-to-users-table/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sync-user-to-users-table/*.html" ]
